### ISSUE TITLE
Adding more containers

### ISSUE THREAD

**Issue by msimonc** [jknanda78/code-splitting-dynamic-routing#2]
For example, how to add a container for Team in .../src/about/index.js to call mapDispatchToProps() when there seems to be a limit of 1 container imported/exported:

import component from './containers/about';

Thanks,

**Comment by msimonc** [comment]
in /src/pages/about/routes/index.js changed the following line:
import(/* webpackChunkName: "Team" */ '../containers/teamContainer')

Now the problem of passing url parameters and page refresh of subroutes remains:

http://localhost:8000/about/team?data=1234

**Comment by jknanda78** [comment]
Hey Mark,

Thanks again for creating an issue. I think the current code doesn't support URL parameters. However, I am planning to update it over this weekend.

**Comment by msimonc** [comment]
Hi Jyoti,  lots of great fundamentals in this repo so no worries,
It looks like that the ability to specify routes decentralized isn't going to work with the dynamic loading which is no big deal: I just merged all the routes at the root level, seems to be fine including sub route page refreshes and URL params.  Still working on a 404 No Match page.
../src/app/routes/routes.js
